"""Initial schema: sensor readings, weather readings, grid state, forecasts, alerts.

Hand-written, not autogenerated: there was no live database available to
diff against when this was written. It must be kept in sync with
app/models/tables.py by hand — tests/test_schema_compiles.py and
tests/test_migrations_offline.py catch drift between the two that shows up
as a compile-time or DDL error, but not a mismatch that's valid SQL on
both sides (e.g. a column present in one but not the other).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-20
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2 as ga
import sqlalchemy as sa

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

H3_CELL_LENGTH = 16


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "sensor_reading",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("source", sa.String(50), nullable=False),
        sa.Column("external_sensor_id", sa.String(100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            ga.Geography(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("pollutant", sa.String(20), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(20), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("latitude BETWEEN -90 AND 90", name="ck_sensor_reading_latitude"),
        sa.CheckConstraint("longitude BETWEEN -180 AND 180", name="ck_sensor_reading_longitude"),
        sa.UniqueConstraint(
            "source",
            "external_sensor_id",
            "pollutant",
            "measured_at",
            name="uq_sensor_reading_identity",
        ),
    )
    op.create_index("ix_sensor_reading_measured_at", "sensor_reading", ["measured_at"])
    op.create_index(
        "ix_sensor_reading_pollutant_measured_at", "sensor_reading", ["pollutant", "measured_at"]
    )
    op.create_index("ix_sensor_reading_geom", "sensor_reading", ["geom"], postgresql_using="gist")

    op.create_table(
        "weather_reading",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("h3_cell", sa.String(H3_CELL_LENGTH), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            ga.Geography(geometry_type="POINT", srid=4326, spatial_index=False),
            nullable=False,
        ),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("wind_direction", sa.Float(), nullable=False),
        sa.Column("precipitation", sa.Float(), nullable=False),
        sa.Column("boundary_layer_height", sa.Float(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("wind_speed >= 0", name="ck_weather_reading_wind_speed"),
        sa.CheckConstraint(
            "wind_direction >= 0 AND wind_direction < 360",
            name="ck_weather_reading_wind_direction",
        ),
        sa.CheckConstraint("precipitation >= 0", name="ck_weather_reading_precipitation"),
        sa.UniqueConstraint("h3_cell", "measured_at", name="uq_weather_reading_cell_time"),
    )
    op.create_index("ix_weather_reading_measured_at", "weather_reading", ["measured_at"])
    op.create_index("ix_weather_reading_h3_cell", "weather_reading", ["h3_cell"])

    op.create_table(
        "grid_state",
        sa.Column("h3_cell", sa.String(H3_CELL_LENGTH), primary_key=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), primary_key=True),
        sa.Column("pm25", sa.Float(), nullable=False),
        sa.Column("pdi", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("wind_speed", sa.Float(), nullable=False),
        sa.Column("wind_direction", sa.Float(), nullable=False),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_grid_state_confidence"),
    )
    op.create_index("ix_grid_state_timestamp", "grid_state", ["timestamp"])

    op.create_table(
        "forecast",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("h3_cell", sa.String(H3_CELL_LENGTH), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_hours", sa.SmallInteger(), nullable=False),
        sa.Column("predicted_pm25", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("forecast_hours > 0", name="ck_forecast_hours_positive"),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_forecast_confidence"),
        sa.CheckConstraint("forecast_time > generated_at", name="ck_forecast_time_after_generated"),
        sa.UniqueConstraint(
            "h3_cell", "generated_at", "forecast_hours", name="uq_forecast_run_horizon"
        ),
    )
    op.create_index("ix_forecast_h3_cell_forecast_time", "forecast", ["h3_cell", "forecast_time"])
    op.create_index("ix_forecast_generated_at", "forecast", ["generated_at"])

    op.create_table(
        "alert",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column("h3_cell", sa.String(H3_CELL_LENGTH), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("message", sa.String(500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_time", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "severity IN ('watch', 'warning', 'critical')", name="ck_alert_severity"
        ),
    )
    op.create_index("ix_alert_h3_cell_created_at", "alert", ["h3_cell", "created_at"])
    op.create_index("ix_alert_severity_created_at", "alert", ["severity", "created_at"])


def downgrade() -> None:
    op.drop_table("alert")
    op.drop_table("forecast")
    op.drop_table("grid_state")
    op.drop_table("weather_reading")
    op.drop_table("sensor_reading")
    # The postgis extension is intentionally left installed: other
    # databases/schemas in the same cluster may depend on it.
