"""F3: per-source health, and pin alerts to the run that produced them.

**`ingestion_source_health`** is the answer to "did this hourly run actually get
data, or did it quietly get nothing?". The pipeline records one row per source
per run, so a run where OpenAQ returned zero rows and Open-Meteo returned 4,954
is distinguishable from a run that never called either - which, before this,
looked identical from outside: both produced a plausible grid.

`status` is deliberately five-valued rather than a boolean:

    present | empty | stale | missing | failed

`empty` and `failed` are the pair that matters most. `empty` means the call
succeeded and the source had nothing to give (a real, reportable condition - a
city with no monitors today). `failed` means we did not get an answer. Both look
like "no data" to anything downstream that only counts rows, and conflating them
is how a source outage turns into a silent zero.

**`alert.run_id`** makes an alert attributable to the run that produced it.
Until this, `alert` had no run column at all, so "alerts for run X" was not a
question the schema could answer, and an alert could not be traced to the inputs
or the model version that caused it. Nullable on purpose: alerts generated before
this revision, and any generated when no v2 run has been published, keep working.
The value is filled in when a run exists; it is not fabricated when one does not.

Revision ID: 0018_f3_source_health
Revises: 0017_f2_report_evidence
Create Date: 2026-09-26
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0018_f3_source_health"
down_revision: str | None = "0017_f2_report_evidence"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_STATUSES = "'present','empty','stale','missing','failed'"


def upgrade() -> None:
    op.create_table(
        "ingestion_source_health",
        sa.Column("id", sa.BigInteger(), primary_key=True),
        sa.Column(
            # Deliberately NOT a foreign key. `ingestion_run` exists in the
            # schema but nothing in the pipeline writes to it - it has been
            # empty throughout - so keying health to it would have produced a
            # column that can never be populated. The pipeline run id is
            # generated by the run itself, and is the same value publication
            # later stamps onto prediction_run, which is what makes
            # "these sources produced this publication" answerable.
            "pipeline_run_id",
            sa.String(length=120),
            nullable=False,
        ),
        # The source's own stable id ('openaq', 'open-meteo', ...), matching
        # ingestion_run.dataset_id rather than a display name, so the two join.
        sa.Column("dataset_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_summary", sa.String(length=500), nullable=True),
        sa.CheckConstraint(f"status IN ({_STATUSES})", name="ck_ingestion_source_health_status"),
        sa.CheckConstraint("item_count >= 0", name="ck_ingestion_source_health_count"),
        # One row per source per run; re-recording a source in the same run
        # replaces its row rather than accumulating duplicates.
        sa.UniqueConstraint(
            "pipeline_run_id",
            "dataset_id",
            name="uq_ingestion_source_health_run_source",
        ),
    )
    op.create_index(
        "ix_ingestion_source_health_run",
        "ingestion_source_health",
        ["pipeline_run_id"],
    )
    # The "is anything actually wrong" index, for an operator scanning the
    # latest few runs rather than one run in depth.
    op.create_index(
        "ix_ingestion_source_health_status",
        "ingestion_source_health",
        ["status", "fetched_at"],
    )

    # Alerts become attributable to a run. Nullable, so no backfill is needed
    # and no existing alert is rewritten.
    op.add_column("alert", sa.Column("run_id", sa.String(length=120), nullable=True))
    op.create_foreign_key(
        "fk_alert_run_id",
        "alert",
        "prediction_run",
        ["run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index("ix_alert_run", "alert", ["run_id", "h3_cell"])


def downgrade() -> None:
    op.drop_index("ix_alert_run", table_name="alert")
    op.drop_constraint("fk_alert_run_id", "alert", type_="foreignkey")
    op.drop_column("alert", "run_id")
    op.drop_index("ix_ingestion_source_health_status", table_name="ingestion_source_health")
    op.drop_index("ix_ingestion_source_health_run", table_name="ingestion_source_health")
    op.drop_table("ingestion_source_health")
