"""Server-side India geofence for citizen fire reports.

`POST /api/v1/reports` is the platform's only open write endpoint, so its
coordinates are attacker-controlled. This module answers "is this report inside
India?" server-side, because the platform is **India-only** and a report in
Kathmandu is not one this platform can act on.

A bounding box would not do: India's extent (roughly 68.1-97.4 E, 6.7-37.1 N)
also contains most of Nepal and Bhutan and a strip of Bangladesh, so a box check
waves through obvious out-of-country reports.

**Basis: ADM1 states and union territories, not the country outline.** The
dissolved `india_country.geojson` the map draws omits small Union Territories -
it has no ring covering Diu - so a point-in-polygon test against it refuses
reports from Indian territory. ADM1 is the administered-level dataset, covers
all 36 states and UTs including the islands, and "inside any state or UT" is
the correct definition of inside India. The geometry is a coarse (~2 km)
Douglas-Peucker simplification of that data, generated by
`scripts/build-india-geofence.py` and committed under `app/domain/data/`.
Publisher and licence (geoBoundaries, ODC-ODbL) travel with the asset.

Two deliberate limits, both stated rather than hidden:

* **Borders and coastlines are approximate at ~2 km.** A report within roughly
  2 km of a land border or shoreline may be accepted or refused incorrectly.
  That is an acceptable trade for refusing gross out-of-country submissions.
* **Points at sea are refused**, which is the correct default for a land-fire
  report.

Because the result is approximate, it only ever gates *acceptance*. It never
raises a report's confidence or contributes to the plume.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_ASSET = Path(__file__).parent / "data" / "india_geofence.json"

#: Publisher of the underlying boundary data, and its terms. Repeated here so a
#: reviewer reading only this module still sees where the geometry came from.
INDIA_BOUNDARY_PUBLISHER = "geoBoundaries ADM1 (https://www.geoboundaries.org)"
INDIA_BOUNDARY_LICENSE = "ODC-ODbL"

#: Reported alongside a refusal so a client can explain *why* it was rejected.
OUTSIDE_INDIA_REASON = (
    "these coordinates are outside India; this platform only accepts reports "
    "located inside the country"
)


class GeofenceAssetError(RuntimeError):
    """The geofence asset is missing or unreadable.

    Raised rather than silently degrading to "accept everything", because an
    unbounded geofence would turn a missing data file into an open endpoint. The
    caller decides what an unavailable geofence means; nothing here guesses.
    """


@lru_cache(maxsize=1)
def _load() -> tuple[tuple[tuple[float, float], ...], ...]:
    """Every ring of every area, largest areas first (see the build script)."""
    if not _ASSET.exists():  # pragma: no cover - a packaging failure, not a logic path
        raise GeofenceAssetError(
            f"India geofence asset missing at {_ASSET}; regenerate it with "
            "`python scripts/build-india-geofence.py`"
        )
    try:
        document: dict[str, Any] = json.loads(_ASSET.read_text(encoding="utf-8"))
        areas = document["areas"]
    except (OSError, json.JSONDecodeError, KeyError) as exc:
        raise GeofenceAssetError(f"India geofence asset at {_ASSET} is unreadable: {exc}") from exc
    if not areas:
        raise GeofenceAssetError(f"India geofence asset at {_ASSET} contains no areas")
    return tuple(
        tuple((float(point[0]), float(point[1])) for point in ring)
        for area in areas
        for ring in area["rings"]
    )


@lru_cache(maxsize=1)
def _bounds() -> tuple[float, float, float, float]:
    """(min_lon, min_lat, max_lon, max_lat) over every ring.

    An O(1) reject before any ray casting: a point outside India's extent cannot
    be inside it, and most abuse attempts are nowhere near India.
    """
    rings = _load()
    lons = [point[0] for ring in rings for point in ring]
    lats = [point[1] for ring in rings for point in ring]
    return min(lons), min(lats), max(lons), max(lats)


def provenance() -> dict[str, str]:
    """How this boundary was produced, for an API response or a log line."""
    return {
        "publisher": INDIA_BOUNDARY_PUBLISHER,
        "license": INDIA_BOUNDARY_LICENSE,
        "basis": "states and union territories (ADM1)",
        "asset": str(_ASSET.relative_to(Path(__file__).resolve().parents[3])),
        "regenerate_with": "python scripts/build-india-geofence.py",
        "note": (
            "coarse (~2 km) simplification used only to validate that a report is "
            "inside India; not a cartographic or legal boundary"
        ),
    }


def _point_in_ring(
    latitude: float, longitude: float, ring: tuple[tuple[float, float], ...]
) -> bool:
    """Ray casting (even-odd rule) against one closed ring.

    Longitude is x, latitude is y. Points exactly on an edge are
    implementation-defined under this algorithm; that ambiguity is one more
    reason the result only gates acceptance, never confidence.
    """
    inside = False
    count = len(ring)
    previous_index = count - 1
    for index in range(count):
        x1, y1 = ring[index]
        x2, y2 = ring[previous_index]
        # Does the edge straddle this latitude? A half-open comparison, so a
        # vertex is counted once rather than twice.
        if (y1 > latitude) != (y2 > latitude):
            crossing_x = (x2 - x1) * (latitude - y1) / (y2 - y1) + x1
            if longitude < crossing_x:
                inside = not inside
        previous_index = index
    return inside


def is_inside_india(latitude: float, longitude: float) -> bool:
    """True when (latitude, longitude) falls inside any Indian state or UT.

    Raises `GeofenceAssetError` if the asset is unavailable, so a caller must
    choose what an unavailable geofence means rather than inherit a silent
    "accept".
    """
    min_lon, min_lat, max_lon, max_lat = _bounds()
    if not (min_lon <= longitude <= max_lon and min_lat <= latitude <= max_lat):
        return False
    return any(_point_in_ring(latitude, longitude, ring) for ring in _load())


def outside_india_detail(latitude: float, longitude: float) -> dict[str, str] | None:
    """A refusal payload when the point is out of country, else None."""
    if is_inside_india(latitude, longitude):
        return None
    return {
        "code": "outside_india",
        "message": OUTSIDE_INDIA_REASON,
        "latitude": f"{latitude:.4f}",
        "longitude": f"{longitude:.4f}",
    }
